<template>
  <body class="__className_20951f">
    <div class="bg-gray-100 dark:bg-blueish-light flex flex-col min-h-screen">
      <Navbar />
      <article class="p-2 m-2 format lg:format-lg dark:format-invert mx-auto">
        <div>
          <center><h2 id="privacy-policy">Privacy Policy</h2></center>

          <p>
            VenturusAI is committed to protecting the privacy of its users. This privacy policy
            explains how we collect, use, and protect your personal information. We will never sell
            your data to any third parties.
          </p>

          <p>
            <strong>Information Collection and Use:</strong> We only collect the information that
            you provide to us when you register or use our platform, including your name and email
            address. We use this information to provide you with the services you request and to
            improve your experience with our platform.
          </p>

          <p>
            <strong>Third-party Services:</strong> We may use third-party services to enhance the
            functionality of our platform and to improve your experience. These services may
            include, but are not limited to, analytics tracking (e.g. Google Analytics) and ensuring
            perfect functionality of the platform. We do not sell or share your personal information
            with any third parties.
          </p>

          <p>
            <strong>Social Registration and Login:</strong> Our platform requires users to have a
            valid account on one of the following social media platforms in order to register or
            access their account: Gmail, Facebook, or Twitter. We use these platforms to
            authenticate your identity and to protect your privacy.
          </p>

          <p>
            <strong>Reports:</strong> By default, all reports generated by our platform are private
            and will not be used or sold by VenturusAI for any commercial or non-commercial
            purposes. However, you can choose to share a report by making it public, VenturusAI
            cannot be held responsible for any parties that access your report as a consequence of
            that. Users own the reports and the commercial rights to them.
          </p>

          <p>
            <strong>Safe Environment:</strong> VenturusAI team will never make use of any of the
            user data and content. You can confidently write your ideas on our platform, as we are
            committed to the safety and privacy of your information.
          </p>

          <p>
            <strong>Data Protection:</strong> We implement appropriate technical and organizational
            measures to protect your personal information from unauthorized access, disclosure,
            alteration, or destruction.
          </p>

          <p>
            <strong>Account Deletion:</strong> To delete your account, please send an email to
            <a href="mailto:support@venturusai.com">support@venturusai.com</a> from the email
            associated with the account you want to remove. All your data will be removed with your
            account. Please note that it takes between 15-30 days for us to respond to all inquiries
            related to account deletion.
          </p>

          <p>
            <strong>Privacy Policy Availability:</strong> This privacy policy is available to all
            users, regardless of their subscription plan.
          </p>

          <p>
            <strong>Contact Us:</strong> If you have any concerns about your privacy or the use of
            your personal information, please contact us at
            <a href="mailto:privacy@venturusai.com">privacy@venturusai.com</a> or through the
            contact form at
            <a href="https://venturusai.com/contact">https://venturusai.com/contact</a>.
          </p>

          <p>
            <strong>Changes to Privacy Policy:</strong> We reserve the right to modify this privacy
            policy at any time, and your continued use of the platform following any changes
            constitutes acceptance of the new privacy policy.
          </p>
        </div>
      </article>
      <FooterP />
    </div>
  </body>
</template>

<script>
import Navbar from '../myComponents/navbar.vue'
import FooterP from '../myComponents/footer.vue'

export default {
  components: {
    Navbar,
    FooterP
  },
  name: 'PrivacyPolicy-P',
  mounted() {
    document.title = 'Privacy Policy - VenturusAI'
  }
}
</script>
