<template>
  <section class="py-3 sm:py-5">
    <div class="px-4 mx-auto max-w-screen-2xl lg:px-12">
      <div class="bg-white dark:bg-blueish-dark relative shadow-md sm:rounded-lg overflow-hidden">
        <div class="border-b dark:border-gray-700 mx-4">
          <div class="flex items-center justify-between space-x-4 pt-3">
            <div class="flex-1 flex items-center space-x-3">
              <h5 class="dark:text-white font-semibold">
                Report examples generated by the VenturusAI team
              </h5>
            </div>
          </div>
          <div
            class="flex flex-col-reverse md:flex-row items-center justify-between md:space-x-4 py-3"
          >
            <div
              class="w-full lg:w-2/3 flex flex-col space-y-3 md:space-y-0 md:flex-row md:items-center"
            >
              <form class="w-full md:max-w-sm flex-1 md:mr-4">
                <div class="relative">
                  <div class="flex">
                    <div class="relative w-full">
                      <div
                        class="pointer-events-none absolute inset-y-0 left-0 flex items-center pl-3"
                      >
                        <svg
                          stroke="currentColor"
                          fill="currentColor"
                          stroke-width="0"
                          viewBox="0 0 24 24"
                          aria-hidden="true"
                          class="h-5 w-5 text-gray-500 dark:text-gray-400"
                          height="1em"
                          width="1em"
                          xmlns="http://www.w3.org/2000/svg"
                        >
                          <path
                            fill-rule="evenodd"
                            d="M10.5 3.75a6.75 6.75 0 100 13.5 6.75 6.75 0 000-13.5zM2.25 10.5a8.25 8.25 0 1114.59 5.28l4.69 4.69a.75.75 0 11-1.06 1.06l-4.69-4.69A8.25 8.25 0 012.25 10.5z"
                            clip-rule="evenodd"
                          ></path>
                        </svg>
                      </div>
                      <input
                        class="block w-full disabled:cursor-not-allowed disabled:opacity-50 text-gray-900 border border-gray-300 bg-gray-50 focus:ring-primary-500 focus:border-primary-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-primary-500 dark:focus:border-primary-500 p-2.5 text-sm pl-10 rounded-lg"
                        id="search"
                        placeholder="Search..."
                        type="search"
                        value=""
                      />
                    </div>
                  </div>
                </div>
              </form>
              <div class="flex items-center space-x-4">
                <div class="hidden">
                  <button
                    type="button"
                    class="w-full md:w-auto flex items-center justify-center py-2 px-4 text-sm font-medium text-gray-900 focus:outline-none bg-white rounded-lg border border-gray-200 hover:bg-gray-100 hover:text-primary-700 focus:z-10 focus:ring-4 focus:ring-gray-200 dark:focus:ring-gray-700 dark:bg-gray-800 dark:text-gray-400 dark:border-gray-600 dark:hover:text-white dark:hover:bg-gray-700"
                    aria-expanded="false"
                    aria-haspopup="menu"
                    id=":r1:"
                  >
                    <svg
                      stroke="currentColor"
                      fill="currentColor"
                      stroke-width="0"
                      viewBox="0 0 24 24"
                      aria-hidden="true"
                      class="h-4 w-4 mr-2 text-gray-400"
                      height="1em"
                      width="1em"
                      xmlns="http://www.w3.org/2000/svg"
                    >
                      <path
                        fill-rule="evenodd"
                        d="M3.792 2.938A49.069 49.069 0 0112 2.25c2.797 0 5.54.236 8.209.688a1.857 1.857 0 011.541 1.836v1.044a3 3 0 01-.879 2.121l-6.182 6.182a1.5 1.5 0 00-.439 1.061v2.927a3 3 0 01-1.658 2.684l-1.757.878A.75.75 0 019.75 21v-5.818a1.5 1.5 0 00-.44-1.06L3.13 7.938a3 3 0 01-.879-2.121V4.774c0-.897.64-1.683 1.542-1.836z"
                        clip-rule="evenodd"
                      ></path>
                    </svg>
                    Filter
                    <svg
                      stroke="currentColor"
                      fill="currentColor"
                      stroke-width="0"
                      viewBox="0 0 24 24"
                      aria-hidden="true"
                      class="-mr-1 ml-1.5 w-5 h-5"
                      height="1em"
                      width="1em"
                      xmlns="http://www.w3.org/2000/svg"
                    >
                      <path
                        fill-rule="evenodd"
                        d="M12.53 16.28a.75.75 0 01-1.06 0l-7.5-7.5a.75.75 0 011.06-1.06L12 14.69l6.97-6.97a.75.75 0 111.06 1.06l-7.5 7.5z"
                        clip-rule="evenodd"
                      ></path>
                    </svg>
                  </button>
                </div>
              </div>
            </div>
            <div
              class="w-full md:w-auto flex flex-col md:flex-row mb-3 md:mb-0 items-stretch md:items-center justify-end md:space-x-3 flex-shrink-0"
            >
              <button
                type="button"
                class="group flex h-min items-center justify-center p-0.5 text-center font-medium focus:z-10 focus:outline-none text-green-900 bg-white border border-greenish-light hover:bg-greenish-lighter hover:text-white focus:ring-greenish-light disabled:hover:bg-white disabled:hover:text-greenish-dark dark:bg-greenish-light dark:text-white dark:border-greenish-light dark:hover:bg-greenish-dark dark:hover:border-greenish-dark dark:disabled:hover:text-white dark:focus:ring-greenish-dark rounded-lg focus:ring-2"
              >
                <span class="flex items-center rounded-md text-sm px-4 py-2">
                  <svg
                    stroke="currentColor"
                    fill="currentColor"
                    stroke-width="0"
                    viewBox="0 0 24 24"
                    aria-hidden="true"
                    class="h-3.5 w-3.5 mr-2"
                    height="1em"
                    width="1em"
                    xmlns="http://www.w3.org/2000/svg"
                  >
                    <path
                      fill-rule="evenodd"
                      d="M12 3.75a.75.75 0 01.75.75v6.75h6.75a.75.75 0 010 1.5h-6.75v6.75a.75.75 0 01-1.5 0v-6.75H4.5a.75.75 0 010-1.5h6.75V4.5a.75.75 0 01.75-.75z"
                      clip-rule="evenodd"
                    ></path>
                  </svg>
                  New report
                </span>
              </button>
            </div>
          </div>
        </div>

        <div class="overflow-x-auto min-h-[30rem]">
          <div data-testid="table-element" class="relative">
            <div class="display-none"></div>
            <table class="w-full text-sm text-left text-gray-500 dark:text-gray-400">
              <thead
                class="group/head text-xs text-gray-700 uppercase bg-gray-100 dark:bg-blueish-dark dark:text-gray-400"
              >
                <tr>
                  <th
                    class="bg-gray-100 dark:bg-blueish-dark px-6 py-3 align-middle cursor-pointer min-w-[20rem] sm:min-w-[30rem]"
                  >
                    Title
                    <svg
                      stroke="currentColor"
                      fill="currentColor"
                      stroke-width="0"
                      viewBox="0 0 24 24"
                      aria-hidden="true"
                      class="h-4 w-4 ml-1 inline-block"
                      height="1em"
                      width="1em"
                      xmlns="http://www.w3.org/2000/svg"
                    >
                      <path
                        fill-rule="evenodd"
                        d="M11.47 4.72a.75.75 0 011.06 0l3.75 3.75a.75.75 0 01-1.06 1.06L12 6.31 8.78 9.53a.75.75 0 01-1.06-1.06l3.75-3.75zm-3.75 9.75a.75.75 0 011.06 0L12 17.69l3.22-3.22a.75.75 0 111.06 1.06l-3.75 3.75a.75.75 0 01-1.06 0l-3.75-3.75a.75.75 0 010-1.06z"
                        clip-rule="evenodd"
                      ></path>
                    </svg>
                  </th>
                </tr>
              </thead>
              <tbody class="group/body divide-y">
                <tr
                  data-testid="table-row-element"
                  class="group/row border-gray-100 bg-white dark:bg-blueish-darker dark:border-blueish-light hover:bg-gray-100 dark:hover:bg-blueish-lighter"
                >
                  <td
                    class="group-first/body:group-first/row:first:rounded-tl-lg group-first/body:group-first/row:last:rounded-tr-lg px-6 py-4 cursor-pointer font-medium max-w-[1px] text-gray-900 dark:text-white"
                  >
                    <a
                      href="https://venturusai.com/report/1ngwV6-a-business-offering-motorboat-rentals-in-tenerife-aiming-to-"
                    >
                      <div data-tooltip-target="tooltip-no-arrow">
                        <div class="whitespace-nowrap overflow-hidden text-ellipsis">
                          A business offering motorboat rentals in Tenerife, aiming to enhance
                          tourists' holiday experience with the option of self-navigation or the
                          added convenience of a professional skipper. The owned fleet consists of 2
                          motorboats, one catamaran, 4 jet skis and one yacht charter.
                        </div>
                      </div>
                      <div
                        id="tooltip-no-arrow"
                        role="tooltip"
                        class="absolute inline-block z-10 rounded-lg py-2 px-3 text-sm font-medium shadow-sm transition-opacity duration-300 invisible opacity-0 bg-gray-900 text-white dark:bg-gray-700 whitespace-normal overflow-hidden"
                      >
                        <div class="relative z-20">
                          A business offering motorboat rentals in Tenerife, aiming to enhance
                          tourists' holiday experience with the option of self-navigation or the
                          added convenience of a professional skipper. The owned fleet consists of 2
                          motorboats, one catamaran, 4 jet skis and one yacht charter.
                        </div>
                        <div
                          class="absolute z-10 h-2 w-2 rotate-45 bg-gray-900 dark:bg-gray-700"
                          data-testid="flowbite-tooltip-arrow"
                          :style="{ top: '-4px', left: '392px' }"
                        >
                          &nbsp;
                        </div>
                      </div>
                    </a>
                  </td>
                </tr>
              </tbody>
            </table>
          </div>
        </div>

        <nav
          class="flex flex-col md:flex-row justify-end items-end md:items-end space-y-3 md:space-y-0 p-2 pb-4"
        >
          <ul class="xs:mt-0 mt-2 inline-flex items-center -space-x-px">
            <li>
              <button
                type="button"
                class="opacity-50 cursor-normal ml-0 rounded-l-lg border border-gray-300 bg-white py-2 px-3 leading-tight text-gray-500 hover:bg-gray-100 hover:text-gray-700 dark:border-gray-700 dark:bg-blueish-darker dark:text-gray-400 dark:hover:bg-blueish-lighter dark:hover:text-white inline-flex"
                disabled=""
              >
                <svg
                  stroke="currentColor"
                  fill="currentColor"
                  stroke-width="0"
                  viewBox="0 0 20 20"
                  aria-hidden="true"
                  class="h-5 w-5"
                  height="1em"
                  width="1em"
                  xmlns="http://www.w3.org/2000/svg"
                >
                  <path
                    fill-rule="evenodd"
                    d="M12.707 5.293a1 1 0 010 1.414L9.414 10l3.293 3.293a1 1 0 01-1.414 1.414l-4-4a1 1 0 010-1.414l4-4a1 1 0 011.414 0z"
                    clip-rule="evenodd"
                  ></path>
                </svg>
                Previous
              </button>
            </li>
            <li aria-current="page">
              <button
                type="button"
                class="w-12 border border-gray-300 py-2 leading-tight dark:hover:bg-blueish-lighter dark:hover:text-white bg-cyan-50 text-cyan-600 hover:bg-cyan-100 hover:text-cyan-700 dark:border-gray-700 dark:bg-gray-700 dark:text-white"
              >
                1
              </button>
            </li>
            <li>
              <button
                type="button"
                class="w-12 border border-gray-300 bg-white py-2 leading-tight text-gray-500 hover:bg-gray-100 hover:text-gray-700 dark:border-gray-700 dark:bg-blueish-darker dark:text-gray-400 dark:hover:bg-blueish-lighter dark:hover:text-white"
              >
                2
              </button>
            </li>
            <li>
              <button
                type="button"
                class="w-12 border border-gray-300 bg-white py-2 leading-tight text-gray-500 hover:bg-gray-100 hover:text-gray-700 dark:border-gray-700 dark:bg-blueish-darker dark:text-gray-400 dark:hover:bg-blueish-lighter dark:hover:text-white"
              >
                3
              </button>
            </li>
            <li>
              <button
                type="button"
                class="w-12 border border-gray-300 bg-white py-2 leading-tight text-gray-500 hover:bg-gray-100 hover:text-gray-700 dark:border-gray-700 dark:bg-blueish-darker dark:text-gray-400 dark:hover:bg-blueish-lighter dark:hover:text-white"
              >
                4
              </button>
            </li>
            <li>
              <button
                type="button"
                class="rounded-r-lg border border-gray-300 bg-white py-2 px-3 leading-tight text-gray-500 hover:bg-gray-100 hover:text-gray-700 dark:border-gray-700 dark:bg-blueish-darker dark:text-gray-400 dark:hover:bg-blueish-lighter dark:hover:text-white inline-flex"
              >
                Next
                <svg
                  stroke="currentColor"
                  fill="currentColor"
                  stroke-width="0"
                  viewBox="0 0 20 20"
                  aria-hidden="true"
                  class="h-5 w-5"
                  height="1em"
                  width="1em"
                  xmlns="http://www.w3.org/2000/svg"
                >
                  <path
                    fill-rule="evenodd"
                    d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z"
                    clip-rule="evenodd"
                  ></path>
                </svg>
              </button>
            </li>
          </ul>
        </nav>
      </div>
    </div>
  </section>
</template>

<script>
export default {
  name: 'example-reports'
}
</script>
